# Generated by Django 5.2 on 2025-04-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_service_userprofile_is_first_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('software_development', 'Software Development'), ('data_science', 'Data Science'), ('cyber_security', 'Cyber Security'), ('robotics', 'Robotics'), ('management', 'Management')], default='software_development', max_length=50),
        ),
    ]
