# Generated by Django 5.2 on 2025-04-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_course_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='course',
            name='course_outline',
            field=models.TextField(default=None, help_text='Detailed breakdown of what the course covers.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='hour_commitment',
            field=models.IntegerField(default=None, help_text='Estimated total hours required to complete the course.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='program_requirements',
            field=models.TextField(default=None, help_text='Requirements to enroll for the course (skills, prior knowledge, etc.).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=None, help_text='Course official start date.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='why_take_this_course',
            field=models.TextField(default=None, help_text='Persuasive reasons why someone should take this course.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Brief description of the course.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(help_text="E.g., '6 weeks', '3 months'", max_length=200),
        ),
    ]
