# Generated by Django 5.2 on 2025-04-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_course_options_course_course_outline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_outline',
            field=models.TextField(blank=True, help_text='Detailed breakdown of what the course covers.', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='hour_commitment',
            field=models.IntegerField(blank=True, help_text='Estimated total hours required to complete the course.', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='program_requirements',
            field=models.TextField(blank=True, help_text='Requirements to enroll for the course (skills, prior knowledge, etc.).', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, help_text='Course official start date.', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='why_take_this_course',
            field=models.TextField(blank=True, help_text='Persuasive reasons why someone should take this course.', null=True),
        ),
    ]
