# Generated by Django 5.2 on 2025-04-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_course_course_outline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
