# Generated by Django 5.2 on 2025-04-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_rename_image_course_image3_course_image4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('title', models.CharField(help_text="Title for this week e.g., 'Introduction to Python'", max_length=255)),
                ('content', models.TextField(help_text='Detailed content for this week.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='web.course')),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
    ]
