# Generated by Django 5.2 on 2025-04-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to deactivate this course.'),
        ),
    ]
